package googletrans

var DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"

var SPECIAL_CASES = map[string]string{
	"ee": "et",
}

var LANGUAGES = map[string]string{
	"abk":      "abkhaz",
	"ace":      "acehnese",
	"ach":      "acholi",
	"aar":      "afar",
	"af":       "afrikaans",
	"sq":       "albanian",
	"alz":      "alur",
	"am":       "amharic",
	"ar":       "arabic",
	"hy":       "armenian",
	"as":       "assamese",
	"ava":      "avar",
	"awa":      "awadhi",
	"ay":       "aymara",
	"az":       "azerbaijani",
	"ban":      "balinese",
	"bal":      "baluchi",
	"bm":       "bambara",
	"bci":      "baoulé",
	"bak":      "bashkir",
	"eu":       "basque",
	"btx":      "batak karo",
	"bts":      "batak simalungun",
	"bbc":      "batak toba",
	"be":       "belarusian",
	"bem":      "bemba",
	"bn":       "bengali",
	"bew":      "betawi",
	"bho":      "bhojpuri",
	"bik":      "bikol",
	"bs":       "bosnian",
	"bre":      "breton",
	"bg":       "bulgarian",
	"bua":      "buryat",
	"yue":      "cantonese",
	"ca":       "catalan",
	"ceb":      "cebuano",
	"cha":      "chamorro",
	"che":      "chechen",
	"zh":       "chinese",
	"zh-cn":    "chinese (simplified)",
	"zh-tw":    "chinese (traditional)",
	"chk":      "chuukese",
	"chv":      "chuvash",
	"co":       "corsican",
	"crh":      "crimean tatar",
	"hr":       "croatian",
	"cs":       "czech",
	"da":       "danish",
	"fa-af":    "dari",
	"dv":       "dhivehi",
	"din":      "dinka",
	"doi":      "dogri",
	"dom":      "dombe",
	"nl":       "dutch",
	"dyu":      "dyula",
	"dzo":      "dzongkha",
	"en":       "english",
	"eo":       "esperanto",
	"et":       "estonian",
	"fao":      "faroese",
	"fij":      "fijian",
	"fil":      "filipino (tagalog)",
	"fi":       "finnish",
	"fon":      "fon",
	"fr":       "french",
	"fy":       "frisian",
	"fur":      "friulian",
	"ful":      "fulani",
	"gaa":      "ga",
	"gl":       "galician",
	"ka":       "georgian",
	"de":       "german",
	"el":       "greek",
	"gn":       "guarani",
	"gu":       "gujarati",
	"ht":       "haitian creole",
	"cnh":      "hakha chin",
	"ha":       "hausa",
	"haw":      "hawaiian",
	"he":       "hebrew",
	"iw":       "hebrew",
	"hil":      "hiligaynon",
	"hi":       "hindi",
	"hmn":      "hmong",
	"hu":       "hungarian",
	"hrx":      "hunsrik",
	"iba":      "iban",
	"is":       "icelandic",
	"ig":       "igbo",
	"ilo":      "ilocano",
	"id":       "indonesian",
	"ga":       "irish",
	"it":       "italian",
	"jam":      "jamaican patois",
	"ja":       "japanese",
	"jv":       "javanese",
	"jw":       "javanese",
	"kac":      "jingpo",
	"kal":      "kalaallisut",
	"kn":       "kannada",
	"kau":      "kanuri",
	"pam":      "kapampangan",
	"kk":       "kazakh",
	"kha":      "khasi",
	"km":       "khmer",
	"cgg":      "kiga",
	"kik":      "kikongo",
	"rw":       "kinyarwanda",
	"ktu":      "kituba",
	"trp":      "kokborok",
	"kom":      "komi",
	"gom":      "konkani",
	"ko":       "korean",
	"kri":      "krio",
	"ku":       "kurdish",
	"ckb":      "kurdish (sorani)",
	"ky":       "kyrgyz",
	"lo":       "lao",
	"ltg":      "latgalian",
	"la":       "latin",
	"lv":       "latvian",
	"lij":      "ligurian",
	"lim":      "limburgish",
	"ln":       "lingala",
	"lt":       "lithuanian",
	"lmo":      "lombard",
	"lg":       "luganda",
	"luo":      "luo",
	"lb":       "luxembourgish",
	"mk":       "macedonian",
	"mad":      "madurese",
	"mai":      "maithili",
	"mak":      "makassar",
	"mg":       "malagasy",
	"ms":       "malay",
	"ms-arab":  "malay (jawi)",
	"ml":       "malayalam",
	"mt":       "maltese",
	"mam":      "mam",
	"glv":      "manx",
	"mi":       "maori",
	"mr":       "marathi",
	"mah":      "marshallese",
	"mwr":      "marwadi",
	"mfe":      "mauritian creole",
	"mhr":      "meadow mari",
	"mni-mtei": "meiteilon (manipuri)",
	"min":      "minang",
	"lus":      "mizo",
	"mn":       "mongolian",
	"my":       "myanmar (burmese)",
	"nhe":      "nahuatl (eastern huasteca)",
	"ndc-zw":   "ndau",
	"nde":      "ndebele (south)",
	"new":      "nepalbhasa (newari)",
	"ne":       "nepali",
	"no":       "norwegian",
	"nus":      "nuer",
	"ny":       "nyanja (chichewa)",
	"oci":      "occitan",
	"or":       "odia (oriya)",
	"om":       "oromo",
	"oss":      "ossetian",
	"pag":      "pangasinan",
	"pap":      "papiamento",
	"ps":       "pashto",
	"fa":       "persian",
	"pl":       "polish",
	"por":      "portuguese (portugal)",
	"pt":       "portuguese (portugal, brazil)",
	"pa":       "punjabi",
	"pa-arab":  "punjabi (shahmukhi)",
	"kek":      "q'eqchi'",
	"qu":       "quechua",
	"rom":      "romani",
	"ro":       "romanian",
	"run":      "rundi",
	"ru":       "russian",
	"sme":      "sami (north)",
	"sm":       "samoan",
	"sag":      "sango",
	"sa":       "sanskrit",
	"sat":      "santali",
	"gd":       "scots gaelic",
	"nso":      "sepedi",
	"sr":       "serbian",
	"st":       "sesotho",
	"crs":      "seychellois creole",
	"shn":      "shan",
	"sn":       "shona",
	"scn":      "sicilian",
	"szl":      "silesian",
	"sd":       "sindhi",
	"si":       "sinhala (sinhalese)",
	"sk":       "slovak",
	"sl":       "slovenian",
	"so":       "somali",
	"es":       "spanish",
	"su":       "sundanese",
	"sus":      "susu",
	"sw":       "swahili",
	"ssw":      "swati",
	"sv":       "swedish",
	"tl":       "tagalog (filipino)",
	"tah":      "tahitian",
	"tg":       "tajik",
	"ber-atn":  "tamazight",
	"ber":      "tamazight (tifinagh)",
	"ta":       "tamil",
	"tt":       "tatar",
	"te":       "telugu",
	"tet":      "tetum",
	"th":       "thai",
	"bod":      "tibetan",
	"ti":       "tigrinya",
	"tiv":      "tiv",
	"tpi":      "tok pisin",
	"ton":      "tongan",
	"ts":       "tsonga",
	"tsn":      "tswana",
	"tcy":      "tulu",
	"tum":      "tumbuka",
	"tr":       "turkish",
	"tk":       "turkmen",
	"tuk":      "tuvan",
	"ak":       "twi (akan)",
	"udm":      "udmurt",
	"uk":       "ukrainian",
	"ur":       "urdu",
	"ug":       "uyghur",
	"uz":       "uzbek",
	"ven":      "venda",
	"vec":      "venetian",
	"vi":       "vietnamese",
	"war":      "waray",
	"cy":       "welsh",
	"wol":      "wolof",
	"xh":       "xhosa",
	"sah":      "yakut",
	"yi":       "yiddish",
	"yo":       "yoruba",
	"yua":      "yucatec maya",
	"zap":      "zapotec",
	"zu":       "zulu",
}

var LANGCODES = reverseMap(LANGUAGES)
